name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Module
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git clone https://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@github.com/Joiint/jugl-android-chat.git
